# <summary>
### This pipeline will scan, test, and release a powershell module into Artifactory.
# </summary>
# <templatesource>
# full-powershell-module  #TODO: Rename this to match the name of this actual file.
# </templatesource>
# <getstarted>
# 1. Go through the variable list below and ensure the values are correct.
# #TODO: Continue steps of directions that need to be complete when using this template.
# </getstarted>
# <morehelp>
# - (https://git.resource.dev.jwac.mil/groups/jwac-apps/-/wikis/Variables)[JWAC Shared Variables]
# - (https://git.resource.dev.jwac.mil/jwac-apps/ci-templates/-/wikis/home)[JWAC Job Template Help]
# #TODO: Add more links to any documentation or help that might be useful when using this template.
# </morehelp>

### <var name="PIPE_PROJ_NAME" required="true" default="Powershell">The name of the Powershell module.</var>  
### <var name="PIPE_PROJ_PATH" default="./$PIPE_PROJ_NAME.ps1">The path to the Powershell module.</var>  
### <var name="PIPE_PACKS_PATH" default="./packs">The path to the packs directory. Used for pulling packages from Artifatory.</var>  
### <var name="PIPE_PESTER_TEST_PATH" default="./tests">The path to the tests directory for Pester output files.</var>  
### <var name="PIPE_PESTER_VERSION" default="Pester.5.3.3.nupkg">The version of Pester being used in the pipeline.</var>  
### <var name="PIPE_PSSCRIPT_ANALYZER_VERSION" default="PSScriptAnalyzer.1.18.3.nupkg">The version of PSScript Analyzer being used in the pipeline.</var>  
### <var name="PIPE_PUSH_TO_ARTIFACTORY" default="false">Boolean value to determine whether or not the script will be published to Artifactory.</var>  

default:
  artifacts:
    expire_in: 3 hours # We are only saving for 3 hours due to the frequency in which this pipeline is ran. Modify to suit your needs.

include:
  - project: 'jwac-apps/ci-templates'
    ref: 'powershell_full_pipe'
    file: 'gitlab-ci/full-pipes/full-Powershell-Module.yml'

variables:
  PIPE_PROJ_NAME: "SBOMResearcher" 
  PIPE_PROJ_PATH: "./${PIPE_PROJ_NAME}/$PIPE_PROJ_NAME.psm1"
  PIPE_PACKS_PATH: "./packs"
  PIPE_PESTER_TEST_PATH: "./${PIPE_PROJ_NAME}/tests"
  PIPE_PESTER_VERSION: "Pester.5.3.3.nupkg"
  PIPE_PSSCRIPT_ANALYZER_VERSION: "PSScriptAnalyzer.1.18.3.nupkg"
  PIPE_PUSH_TO_ARTIFACTORY: "true"
  PIPE_MODULE_PROCESS: "SBOM-Researcher.psm1"
  PIPE_PROJ_AUTHOR: "Kurt Hockaday"
  PIPE_PROJ_DESCRIPTION: "Accepts 1 or more SBOMs and queries various vulnerability databases, generating a report and JSON objects with the results"
  PIPE_FUNCTIONS_TO_EXPORT: "SBOMResearcher"

