name: Pester
on: push
permissions:
  contents: read

jobs:
  pester-tests:
    name: Pester tests
    runs-on: windows-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Perform all Pester tests from the SBOMResearcher tests directory
        shell: pwsh
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -Confirm:$false -RequiredVersion 5.6.1 -Force
          . .\SBOMResearcher.ps1
          Invoke-Pester -Script .\tests -OutputFile "./Pester.XML" -OutputFormat "NUnitXML" -Passthru -Verbose
      - name: Upload test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Pester-Version-Tests
          path: Pester.XML
    if: ${{ always() }}
